name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  REGISTRY: registry.hub.docker.com
  IMAGE_NAME: svetvel/mecho
  USERNAME: svetvel 
  PASSWORD: aa
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: svetvel
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ IMAGE_NAME }}:latest
        labels: Anna
